### ISSUE TITLE
Action fails: FileNotFoundError: [Errno 2] No such file or directory: 'wordlist.txt'

### ISSUE THREAD

**Issue by edumco** [rojopolis/spellcheck-github-actions#10]
Fail to check project: https://github.com/edumco/Algorithms-Explanation

Log attached: [logs_1.zip](https://github.com/rojopolis/spellcheck-github-actions/files/4500690/logs_1.zip)

**Comment by M1ke** [comment]
I get the same issue as this.

**Comment by mrbusche** [comment]
I was able to get this working in this commit https://github.com/mrbusche/recipesapp/commit/5d55373c23c6e2ff1eeb980bb908424fb7de7828 You need spellcheck.yaml and an empty wordlist.txt in the root to make it work.

**Comment by edumco** [comment]
Still not working **:(**

repo: https://github.com/edumco/Algorithms-Explanation/tree/spellcheck

```log
Traceback (most recent call last):
  File "/usr/local/bin/pyspelling", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__main__.py", line 34, in main
    debug=args.debug
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__main__.py", line 59, in run
    debug=debug
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 672, in spellcheck
    for result in spellchecker.run_task(task, source_patterns=sources):
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 316, in run_task
    for sources in self._walk_src(source_patterns, glob_flags, glob_limit, self.pipeline_steps, expect_match):
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 216, in _walk_src
    '\n'.join('- {}'.format(target) for target in targets)
RuntimeError: None of the source targets from the configuration match any files:
- **/*.py
```

**Comment by mrbusche** [comment]
Ha, actually turns out the working example I found on Github was using `UnicornGlobal/spellcheck-github-actions@master` oops!

**Comment by edumco** [comment]
So how can I help fix this?

**Comment by jonasbn** [comment]
Hi @edumco 

I have added a diagnostics section to the documentation, I hope it explains the remedy better.

I have made a first shot at a fix introducing the induction of an empty `wordlist` file matching the default configuration. But I am not satisfied with the solution, since I do not like the idea of inducing files like this.

Please let me know if you have any ideas or evaluate the documentation and let me know if it is any help at all.

**Comment by jonasbn** [comment]
Release 0.4.0, with the solution described above included, has just been published to the GitHub Marketplace. 

I am closing this issue for now. I hope a better solution will present itself as I get more hands on with the problem area and the code for this action.
