### ISSUE TITLE
Investigate possible issue with error count PySpelling

### ISSUE THREAD

**Issue by jonasbn** [rojopolis/spellcheck-github-actions#15]
Hi @edumco 

Thanks for the elaborate feedback. I have compiled your comments to this list:

_<snip>_

- [ ] Investigate possible issue with error count **PySpelling**

_<snip>_

_Originally posted by @jonasbn in https://github.com/rojopolis/spellcheck-github-actions/pull/12#issuecomment-636716234_

**Comment by facelessuser** [comment]
Pyspelling doesn't output error count: https://github.com/facelessuser/pyspelling/blob/master/pyspelling/__main__.py#L75.

That is just the exit code, which is simply 1 if there was a failure and 0 if there was no failure. It's just a boolean pass or fail currently. Failure for spelling, failure to read file, doesn't matter, the exit code is 1.

**Comment by facelessuser** [comment]
Source is of mistaken count is here, and we see it is in fact just referencing the exit code, not a real count: https://github.com/rojopolis/spellcheck-github-actions/blob/master/entrypoint.sh#L38.

I think people assume the `(1)` means number of files, when it doesn't. I would just remove the error code as the message itself indicates pass or fail.

**Comment by jonasbn** [comment]
Hi @facelessuser 

I see the reason for the misunderstanding and the error code was mostly included for myself when I restructured the entry point.

They do not have significant value since they can be obtained by querying the shell, since they are still emitted, I agree that they can go
