### ISSUE TITLE
Help: Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or verified in the GitHub Marketplace.

### ISSUE THREAD

**Issue by leomonan** [rojopolis/spellcheck-github-actions#154]
Hello ,
    We got this error when try to use the spellcheck github actions in our enterprise github repo: 
[Error: .github#L1]
rojopolis/spellcheck-github-actions@0.30.0 is not allowed to be used in xxxxrepo. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or verified in the GitHub Marketplace.

Could you please let me know if there are some solutions?
thanks.

**Comment by jonasbn** [comment]
Hi @leomonan 

I just did a quick read up on this:

- https://docs.github.com/en/apps/publishing-apps-to-github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

It is not really an option for this repository. 

However a suggestion could be to create a fork of this repository to your own organisation and use that, then once in a while you can pull from this repository.

```shell
git remote add upstream git@github.com:rojopolis/spellcheck-github-actions.git
git pull upstream master
```

I have done this before for a repository we used in a work set up.

You can either schedule updates or you can keep an eye on the releases.
