### ISSUE TITLE
can you add a feature that ignores specific sections in an md file?

### ISSUE THREAD

**Issue by clubanderson** [rojopolis/spellcheck-github-actions#162]
I have UIDs in some of our codeblocks.  I do not want to ignore codeblocks altogether.  Is it possible to ignore specific sections of text?

**Comment by jonasbn** [comment]
Hi @clubanderson 

The GitHub Action is just a wrapper around [PySpelling](https://github.com/facelessuser/pyspelling) you should direct you inquiry to that specific repository.

We can add features which have to do with the action and it's execution, but I believe that what you request would be a core feature, so the actual PySpelling component would be the place of interest.

**Comment by jonasbn** [comment]
Hi @clubanderson 

This is actually a nifty idea, I have see many other _linters_ which do something similar.

But it is up to @facelessuser, he is the maintainer of [PySpelling](https://github.com/facelessuser/pyspelling)

**Comment by clubanderson** [comment]
I think this would be a great addition for markdown support.
