### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by edumco** [rojopolis/spellcheck-github-actions#19]
Would be nice to have a silent mode so it doesn't break CI for some files or branches

We could have an breaking action for PR and a silent for the branches

What do you think about it?

**Comment by jonasbn** [comment]
@edumco sounds like a good idea. Hacktoberfest is coming up, perhaps we good look into it there

**Comment by jonasbn** [comment]
Hi @edumco 

I have been thinking about this and got to a point where I got stuck on your _silent mode_ request.

1. First I was thinking, you just wanted it to run, but not log anything, which is doable.
2. Then I learned the other day that  you can target your workflows to specific branches [See GitHub Actions documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions)

Which brings me to your original request. So what do you mean when you say _silent mode_ ?

The first part could be addressed as a feature implementation. 

The second part should be doable using workflow configuration, which then just require some more documentation on how to enable this or perhaps a combination of an implementation and workflow management.

Looking forward to hearing from you.

**Comment by edumco** [comment]
@jonasbn Im sorry i loose track on my github account (2020 was hard)

I realized that what I was suggesting fits on the second category: Make documentation more clear about where it should break the pipeline

**Comment by edumco** [comment]
I'm closing this issue cause now I believe the documentation already covers it
