### ISSUE TITLE
how to use for other languages?

### ISSUE THREAD

**Issue by Guite** [rojopolis/spellcheck-github-actions#3]
I tried to get this action working several weeks ago but failed because it seems that only English is included. Is there any possibility to tell this action to install for example German support? I guess this would require installing additional packages in the docker file, so probably not easy...

**Comment by rojopolis** [comment]
Hi @Guite this is really just a small wrapper around the excellent [pyspelling](https://facelessuser.github.io/pyspelling/) package.  If pyspelling supports additional languages, then it would be trivial to add the support to the action.  Feel free to research it and create a pull request here with your proposed changes!

**Comment by Guite** [comment]
> PySpelling is a wrapper around either Aspell or Hunspell.

I thought as you are installing `aspell` in your docker file, it would be a matter of installing for example `aspell-de` additionally (or `hunspell-de`).

But I have not really an idea if and how PySpelling would support this. Can't find anything in it's docs about non-english languages.

**Comment by Guite** [comment]
For clarification: at the end this feature is not really important (as I know how to write correctly). It would just be a nice to have addition for a workflow which deploys a blog site for example, so that typos could be found easier and faster.

**Comment by facelessuser** [comment]
Pyspelling uses whatever dictionary you give it. It is a wrapper around aspell and hunspell. While I only write in English, I can't think of a reason why it wouldn't work for other languages. You could already configure your own action, it isn't too difficult: https://facelessuser.github.io/pyspelling/#usage-in-ci.

**Comment by Guite** [comment]
Thanks for the pointer.
