### ISSUE TITLE
spellcheck.yaml is not used

### ISSUE THREAD

**Issue by chipitsine** [rojopolis/spellcheck-github-actions#4]
hello,

I defined my own spellcheck.yaml, there are only *.txt pattern

https://github.com/chipitsine/haproxy

however, runner complains it cannot find *.py, I suspect it tries to use its default config

https://github.com/chipitsine/haproxy/runs/446656168?check_suite_focus=true

**Comment by chipitsine** [comment]
@rojopolis , can you have a look please ?

**Comment by darrynten** [comment]
@chipitsine I ran into a similar issue.

The `.yml` file in your repo should use the `.yaml` extension (with the `a`) or it is not detected.

**Comment by chipitsine** [comment]
Thanks, I will try

**Comment by chipitsine** [comment]
I tried both spellcheck.yml

https://github.com/chipitsine/haproxy/runs/475469193

and spellcheck.yaml

https://github.com/chipitsine/haproxy/runs/475464511


neither works.

@darrynten , can you provide a link to your repo ?

**Comment by codygreen** [comment]
I'm seeing the same issue. @chipitsine, did you find a solution or just stoped using the action?

**Comment by chipitsine** [comment]
I ended with codespell

https://github.com/haproxy/haproxy/blob/master/.github/workflows/codespell.yml

**Comment by facelessuser** [comment]
There are a number of options out there, but this is built one is built on pyspelling and doesn't have to be done with this action. You can easily configure it yourself in GitHub actions: https://facelessuser.github.io/pyspelling/#usage-in-ci. You would also configure your own `.pyspelling.yml` as well.

**Comment by jonasbn** [comment]
I am working on a release 0.4.0 introducing a limited default configuration, aiming only at Markdown since this more certain to work out of the box for most repositories and not giving non-python repositories initial headaches.

The release also introduces support for `yml` in addition to `yaml`.

Please refer to the updated documentation for details for now, I am attempting to work out how to get the privilege to push the release to the Marketplace.

**Comment by jonasbn** [comment]
Hello, 

0.4.0 has just been uploaded to the GitHub Market place. Please let me know if you experience any issues in regard to this or any other issues with 0.4.0 for that matter.

Take care and stay safe,

jonasbn
