### ISSUE TITLE
Ignore casing issues

### ISSUE THREAD

**Issue by tomkerkhove** [rojopolis/spellcheck-github-actions#44]
Is it possible to define a word once in the word list, and allow all casings for it?

**Comment by facelessuser** [comment]
If you are using Aspell, you can use the `ignore-case` spell checker option: https://facelessuser.github.io/pyspelling/configuration/#spell-checker-options.

You would just specify the boolean:

```yaml
  aspell:
    ignore-case: true
```

Basically, such behavior is controlled by the spellchecker. You either specify multiple casings in your word list, or you turn off casing altogether.

Each spell checker has different options and such, so if you are using Huspell, casing is likely configured differently.

**Comment by tomkerkhove** [comment]
Perfect, thank you - I've missed that one!

**Comment by jonasbn** [comment]
I have added this as a tip to the newly added Tips section in the documentation, thanks @facelessuser
