### ISSUE TITLE
Marketplace still using 0.2.0 which has wordlist.txt issue.

### ISSUE THREAD

**Issue by sbates130272** [rojopolis/spellcheck-github-actions#5]
Can you bump the marketplace latest to 0.3.0 so people don't hit the wordlist.txt issue (issue #1) please?

**Comment by jonasbn** [comment]
I cannot push release 0.3.0 to the Marketplace it might have to be the repository owner. I have contacted GitHub for clarification, since this is not detailed in the documentation

**Comment by jonasbn** [comment]
Please see [the response to my question to the support forum](https://github.community/t/who-can-publish-an-action-to-the-marketplace/115602/3).

I suspect that the requirements for publishing and action was changed over time and 0.3.0 did not meet these requirements, when lacking an `action.yml` file. 

The file has been added to release 0.4.0, which has been published to the Marketplace.

Please get back to me if you experience any issues with the 0.4.0 release.

Take care and stay safe,

jonasbn
