### ISSUE TITLE
Latest container version failing on runners due to architecture mismatch

### ISSUE THREAD

**Issue by chrispat** [rojopolis/spellcheck-github-actions#79]
@jonasbn it appears that the latest version of the spellcheck container has been published as arm64 rather than amd64 or for multiple platforms.  This issue is causing the action to fail on the GitHub Actions runners.  

Can you either rollback the tags or publish an image for amd64?

**Comment by jonasbn** [comment]
Oh dear, I will look at it right away and push a new image

**Comment by jonasbn** [comment]
This has been fixed with [release 0.21.1](https://github.com/rojopolis/spellcheck-github-actions/releases/tag/0.21.1)

Sorry about the inconvenience, I will take action to have GitHub Actions build and publish the Docker images, to eliminate the the option of _human error_

**Comment by chrispat** [comment]
Thank you for the rapid response here, we really appreciate it.  We have integrated authentication between GitHub Actions and GitHub Container Registry.  I would recommend you move to publishing your actions container to GHCR so you can use the integrated GITHUB_TOKEN rather than a PAT.  There is a starter workflow for publishing a container to GHCR that should get you most of the way there.

**Comment by jonasbn** [comment]
Hi @chrispat I will have a look at it, my problem might be that I am not the owner of the repository, just the maintainer. I will do some reading and write up my notes in #80, but I think the last time I looked at it, it was a no go.
