### ISSUE TITLE
Support for french

### ISSUE THREAD

**Issue by gcattan** [rojopolis/spellcheck-github-actions#87]
Hi, 
Is it possible to add support for french language?
Thanks!

**Comment by jonasbn** [comment]
Hi @gcattan - oui!

I will have a look into adding support for French.

**Comment by gcattan** [comment]
Thank you :)

**Comment by jonasbn** [comment]
Hi @gcattan 

I have just pushed release 0.23.0 to the GitHub Market place, please do not hesitate to reach out if you experience any issues.

I did a basic test on the French dictionary and this is my first (actually second) release from Apple Silicon (M1), but it seems as if I have gotten my Docker build process to work.

**Comment by gcattan** [comment]
Hi @jonasbn , 

Thank you so much :) It worked as expected, this is perfect :)
